# -*- coding: utf-8 -
from tinydb import TinyDB, Query

db = TinyDB('development.json')
db.insert({'text': '1987年4月8日リリース。TVアニメ『CITY HUNTER』の初代エンディングテーマ', 'label': 1})
db.insert({'text': 'TMの代名詞ともいえるこの曲は、リリースされて20年以上経った今でも根強い人気がある。', 'label': 1})
db.insert({'text': '1989年には『GET WILD\'89』(～エイティーナインorハチキュー)というタイトルでリミックスヴァージョンが発売された。', 'label': 1})
db.insert({'text': 'シングル『GET WILD DECADE RUN』(～ディケイド・ラン)を発売。', 'label': 1})
db.insert({'text': '悪魔に魂を売る気はない！！悪魔はドブネズミにおとる', 'label': 1})
db.insert({'text': 'XYZ…もう後が無い、それがやつへの依頼方法', 'label': 1})
db.insert({'text': 'もっこり', 'label': 1})
db.insert({'text': 'だからこそ おれのような男がいるのさ…!!', 'label': 1})
db.insert({'text': '悪魔に魂を売る気はない!! 悪魔はドブネズミにおとる!!', 'label': 1})
db.insert({'text': 'コミックス1巻134頁「恐怖のエンジェルダストの巻」より', 'label': 1})
db.insert({'text': 'あいにくこの壁がぶち抜けるかどうかあやしい豆鉄砲でねえ', 'label': 1})
db.insert({'text': 'おれは香を奴から守ります!! そしてさよなら……です!! ', 'label': 1})
db.insert({'text': 'よく覚えておくんだな 自分のためではなく他人のために戦える真の男のうしろ姿を', 'label': 1})
db.insert({'text': '海原……おれが今…何を考えているかわかるか？', 'label': 1})
db.insert({'text': 'ミック……まるでおまえのぬけがらと戦ってるようだよ……', 'label': 1})
db.insert({'text': 'そうエンジェル・ダストだ！！しかも新型で強力', 'label': 1})
db.insert({'text': 'そんな…2人は親友も同然じゃない！！なんのために争わなくちゃなんないの！？', 'label': 1})
db.insert({'text': 'エンジェルダスト！！', 'label': 1})
db.insert({'text': '香に伝えることは……？', 'label': 1})
db.insert({'text': 'しばらくの間地獄はさびしいかもしれんがすぐににぎやかにしてやるよ………', 'label': 1})
db.insert({'text': '槇村……！！', 'label': 1})
db.insert({'text': '悪魔に魂を売る気はない！！悪魔はドブネズミにおとる', 'label': 1})
db.insert({'text': 'のわあっ!! おぼえてろォ!! 冴子めェ!!', 'label': 1})
db.insert({'text': 'ぶゎかいうんじゃねっ、おれのもっこりはまだ１０代の元気をたもっとるんだ!!', 'label': 1})
db.insert({'text': 'あんな男女みたいのともっこりだなんて この世の地獄だぜ!!', 'label': 1})
db.insert({'text': 'は〜い あなたは今から三つ数えると目が覚めまぁ〜す。目が覚めると獠(リョウ)ちゃんが大好きになってもっこりがしたくなります、いいですね〜♡ い〜ち、にぃ〜の…', 'label': 1})
db.insert({'text': 'あいつはおたくが手を汚す程の値打ちもない。だからこそ、オレのような男が要るのさ・・・', 'label': 1})
db.insert({'text': 'しばらくの間地獄はさびしいかもしれんがすぐににぎやかにしてやるよ', 'label': 1})
db.insert({'text': 'あの戦争の中であんたの存在だけがおれの人間としての唯一の―――やすらぎだった…すべてだった……', 'label': 1})
db.insert({'text': 'オレは一度引き受けた仕事は必ずやり遂げる主義でね。例え、未来の妻じゃ無くなってもな。', 'label': 1})
db.insert({'text': 'オリジナルの詞に対して一部小室哲哉によって追加詞・改詞されている部分がある。', 'label': 1})
db.insert({'text': '何だあの不敵な笑みは・・・俺が一緒でも2人きりになれる手でもあるというのか それともまさか。。今夜夜這を。。', 'label': 1})
db.insert({'text': '今度会う時までにシティーハンターという名を覚えておくことだ', 'label': 1})
db.insert({'text': 'いくら逃げても、相手は容赦しない だが君が戦うというなら、俺がナイトになろう 俺はそのために来た', 'label': 1})
db.insert({'text': 'まいったな〜 ボスが美人だと、獠は頼りにならないわね', 'label': 1})
db.insert({'text': 'また死にたくなったら言ってくれ 女性へのアフターサービスは万全なんだ', 'label': 1})
db.insert({'text': '獠、あなたには新しい相棒が必要よね', 'label': 1})
db.insert({'text': 'おたくは自分の命を始末料にした だったら俺がその命をもらう おたくの命があるかぎり 俺を恋人だと思ってくれ', 'label': 1})
db.insert({'text': 'あいつは・・おたくが手を汚す程の値打ちもない・・・だからこそ・・俺のような男がいるのさ。。', 'label': 1})
db.insert({'text': 'リョウ…俺の依頼を受けてくれるか…？報酬は…', 'label': 1})
db.insert({'text': '悪魔に魂を売る気はない！悪魔はドブネズミに劣る', 'label': 1})
db.insert({'text': 'シティーハンター -XYZ-', 'label': 1})
db.insert({'text': 'なお本作ではヒロインである槇村香', 'label': 1})
db.insert({'text': '冴羽 獠（さえば りょう）', 'label': 1})
db.insert({'text': '槇村 香（まきむら かおり）', 'label': 1})
db.insert({'text': '獠の親友で相棒。警察官だった父親の志を受け継いで自らも刑事となる', 'label': 1})
db.insert({'text': '喫茶キャッツアイ', 'label': 1})
db.insert({'text': '通称・海坊主またはファルコン。元傭兵で獠と互角の凄腕を持つ同業者。', 'label': 1})
db.insert({'text': '獠に「タコ坊主」と呼ばれる', 'label': 1})
db.insert({'text': '海坊主の相棒で、美人スイーパー。', 'label': 1})
db.insert({'text': '空跳ぶオシリ', 'label': 1})
db.insert({'text': '野上 冴子（のがみ さえこ）', 'label': 1})
db.insert({'text': '「警視庁の女狐」と呼ばれる、妖艶な美人刑事。鼻筋が通った品のいい顔立ちをしている。野上警視総監の長女。槇村秀幸とは同僚だった。', 'label': 1})
db.insert({'text': '熊本地震（くまもとじしん）', 'label': 0})
db.insert({'text': '熊本県阿蘇地方及び大分県においても規模の大きな地震が相次いで発生した', 'label': 0})
db.insert({'text': 'インターネット・サービス', 'label': 0})
db.insert({'text': '最初の地震から約28時間後', 'label': 0})
db.insert({'text': '横ずれ断層型の内陸地殻内地震である', 'label': 0})
db.insert({'text': '余震域外での地震活動の活発化', 'label': 0})
db.insert({'text': '地震活動の広がり方をしていることから', 'label': 0})
db.insert({'text': 'なお本作ではヒロインである槇村香が「男受けするキャラではない」という判断から、毎回男受けする「美女」を登場させていた。', 'label': 1})
db.insert({'text': 'S3のデータを利用する設定', 'label': 0})
db.insert({'text': '以下のコマンドを実行して問題なくS3にアクセスできることを確認します。', 'label': 0})
db.insert({'text': 'ツイート収集結果はこんな感じ', 'label': 0})
db.insert({'text': 'Spark/PySparkでツイート分析してみた', 'label': 0})
db.insert({'text': 'バイト文字列ではなくユニコード文字列に寄せる', 'label': 0})
db.insert({'text': '世界中に散らばった7つの玉を全てを集めると、どんな願いでも1つだけ叶えられるという秘宝「ドラゴンボール」', 'label': 0})
db.insert({'text': '中国の伝奇小説『西遊記』をモチーフにしており、主人公の名前も同作品の主要登場人物である神仙・孫悟空から名付けられている。', 'label': 0})
db.insert({'text': '地球の人里離れた山奥に住む尻尾の生えた少年・孫悟空はある日、西の都からやって来た少女ブルマと出会う。', 'label': 0})
db.insert({'text': '「ポコペンポコペン誰がつついた…」', 'label': 0})
db.insert({'text': '摩訶不思議アドベンチャー', 'label': 0})
db.insert({'text': 'クリリンvs餃子', 'label': 0})
db.insert({'text': '「どんな願いもひとつだけかなえてやろう…」「イクラを山ほど食べたいーーっ！！」', 'label': 0})
db.insert({'text': '大遅刻ですが牛蒡の日でしたね。 一言言わせてください。 バーダック最高。', 'label': 0})
db.insert({'text': '覚悟はよろしいですね', 'label': 0})
db.insert({'text': 'バーダックいたw 僕のドラゴンボール資料半端ねぇwww', 'label': 0})
db.insert({'text': 'ドラゴンボールメインのブログやってます！', 'label': 0})
db.insert({'text': '5月1日はバーダックの日！と、知ったのでお祝いです(*´∀`)♪', 'label': 0})
db.insert({'text': '『ドラゴンボール』バンプレスト「超造集」が原作カラーでリターンマッチ！ ', 'label': 0})
db.insert({'text': 'ドラゴンボール地図はめ絵', 'label': 0})
db.insert({'text': 'ピッコロ「しまった！！」', 'label': 0})
db.insert({'text': 'ドラゴンボールZ ドッカンバトル', 'label': 0})
db.insert({'text': 'ドラゴンボールヒーローズ☆4(HGD7-43)フロスト、ゲットー！(しかも1回で…！)', 'label': 0})
db.insert({'text': '手ごわいやーつほど わくわくも～でっかいぜー ドッカンドッカン…', 'label': 0})
db.insert({'text': '「パラガスZ 〜本来の計画〜」', 'label': 0})
db.insert({'text': '『DANDAN心惹かれてく』がきました。おそらく私が初めて見たドラゴンボールはこれの再放送かもしれません。', 'label': 0})
db.insert({'text': 'クリリンに服を脱がされるブルマｗ', 'label': 0})
db.insert({'text': '悟空じいちゃんと再会', 'label': 0})
db.insert({'text': 'ドドリアさんとザーボンさんを追加ですよ', 'label': 0})
db.insert({'text': '悟空より結構強い奴等が死ぬ程ビビってる全王様に勝てる奴とかいるの？', 'label': 0})
db.insert({'text': 'ドラゴンボール好きはRTふぁぼお願いします♪ ', 'label': 0})
db.insert({'text': 'ドラゴンボールで1番好きな歌4曲 とくに「一人じゃない」が1番好きです。', 'label': 0})
db.insert({'text': 'ゴールデンフリーザ＆メタルクウラ', 'label': 0})
db.insert({'text': 'ああー心がドッカンドッカンするんじゃー', 'label': 0})
db.insert({'text': 'ドラゴンボール超から孫悟空が登場！', 'label': 0})
db.insert({'text': 'ムチャするヤムチャ', 'label': 0})
db.insert({'text': 'ドラゴンボールZドッカンバトルのデータを販売してます！先送りはできませんが、詐欺はしません！詳しくはDMで！', 'label': 0})
db.insert({'text': '今日のTシャツは亀一門。', 'label': 0})
db.insert({'text': '太っちょの魔神ブウがギガンティックシリーズに登場', 'label': 0})
db.insert({'text': 'ガンティックシリーズに「セルJr.」が登場', 'label': 0})
db.insert({'text': 'シティハンターXYZ edition購入特典の「リョウのプロポーズ」が着ました！今から見る！！', 'label': 1})
db.insert({'text': '特にエピローグの素晴らしさ。これCHのリョウと香だよなぁ♪', 'label': 1})
db.insert({'text': 'シティーハンターのハンマーで、叩いてみたい', 'label': 1})
db.insert({'text': '9位にシティーハンター入ってる…', 'label': 1})
db.insert({'text': 'TM NETWORKの代表曲。テレビアニメ『シティーハンター』（読売テレビ系）のエンディングテーマとなった', 'label': 1})
db.insert({'text': '海外のプロデューサー・ピート・ハモンドによるリミックスバージョン『GET WILD \'89』がリリースされ', 'label': 1})
db.insert({'text': '小室によるオーバーダビングを施した『Get Wild (techno overdub mix)』が収録されたリミックスアルバム『TMN CLASSIX 1』がリリースされた。', 'label': 1})
db.insert({'text': 'リミックス、ライヴバージョンが1枚のCDにまるごと収録されている。なお、『ALL the “Get Wild” ALBUM』のジャケットは1987年当時のデザイン（アナログ盤）を復刻させた仕様となっている。', 'label': 1})
db.insert({'text': '凶悪犯冴羽獠の最期', 'label': 1})
db.insert({'text': '1989年にはビクター・ファンタスティック・オーケストラによって「GET WILD \'89」のインストゥルメンタルバージョンが発表されている。', 'label': 1})
db.insert({'text': 'デイブ・ロジャースによる逆カバーアルバム「TMNソング・ミーツ・ディスコ・スタイル」に収録されている「Get Wild」は、全編英詞である。', 'label': 1})
db.insert({'text': '凶悪犯冴羽獠の最期', 'label': 1})
db.insert({'text': 'シティーハンタースペシャルのEDテーマに使われた、GET WILD ～CITY HUNTER SPECIAL\'97 VERSION～ / NAHO。', 'label': 1})
db.insert({'text': 'Get Wild（『シティーハンター』エンディング・テーマ） 作詞：小室みつ子／作曲・編曲：小室哲哉', 'label': 1})
db.insert({'text': '凶悪犯冴羽獠の最期', 'label': 1})
db.insert({'text': 'ルフィはシャンクスを貶める山賊たちから怒りを買い、海に投げ込まれてしまう', 'label': 0})
db.insert({'text': 'ルフィとコビーは海軍基地の町「シェルズタウン」に到着する', 'label': 0})
db.insert({'text': 'ゾロを仲間に加えたルフィは、次に訪れた「オレンジの町」で、海賊専門の泥棒ナミと出会う', 'label': 0})
db.insert({'text': 'CITY HUNTER - 愛よ消えないで', 'label': 1})
db.insert({'text': 'ユニオンテオーペの首領で、獠の育ての父。獠とどことなく顔つきが似ている。', 'label': 1})
db.insert({'text': '海原 神', 'label': 1})
db.insert({'text': '東の海の大物海賊達を次々に打ち破ったルフィの情報は海軍にも伝わり、ルフィには東の海最高となる3000万ベリーの懸賞金が懸けられる。', 'label': 0})
db.insert({'text': '「東の海（イーストブルー）」のフーシャ村に住む少年モンキー・D・ルフィ', 'label': 0})
db.insert({'text': 'ユニオンテオーペからの依頼のターゲットとして名前が登場。その後、入院する獠を狙う組員が登場している。', 'label': 1})
db.insert({'text': '女好きで普段は節操がないが、仕事となると超一流で銃の名手', 'label': 1})
db.insert({'text': '飛行機事故時のトラウマで飛行機恐怖症', 'label': 1})
db.insert({'text': '恐怖のエンジェルダストの巻', 'label': 1})
db.insert({'text': 'がんばれ!香ちゃん!!の巻', 'label': 1})
db.insert({'text': '週刊少年ジャンプに連載されていた北条司によるハードボイルド漫画作品', 'label': 1})
db.insert({'text': '裏の世界NO.1スイーパー', 'label': 1})
db.insert({'text': '100tハンマー', 'label': 1})
db.insert({'text': 'シティ・ハンター~愛よ消えないで~', 'label': 1})
db.insert({'text': '無類のスケベ、女好きで依頼人にもっこりして、ちょっかいを出すため香に天誅を食らっている', 'label': 1})
db.insert({'text': '警官であった槇村秀幸の父が追跡中、事故死させた久石純一の娘', 'label': 1})
db.insert({'text': 'ある人身売買組織の捜査中におとり捜査官の婦人警官が殉職してしまったため、責任をとって警察を辞め獠とコンビを組む', 'label': 1})
db.insert({'text': '元傭兵で獠と互角の凄腕を持つ同業者。後に喫茶キャッツアイの店主', 'label': 1})
db.insert({'text': '妻のソフィの父親の多額の借金を抱え、夫婦関係がとても悪かった', 'label': 0})
db.insert({'text': 'マフィアにジミーが近所にいる事を密告してお金をもらおうと考え、ニコラスにマフィアのところまで行かせる。', 'label': 0})
db.insert({'text': '冴子とは刑事時代の相棒であり、美人の冴子に対して槇村の容貌が冴えないため、警視庁の「月とスッポン」とあだ名されていた', 'label': 1})
db.insert({'text': '劇中序盤早々に麻薬密売組織ユニオン・テオーペに殺されてしまうため、下の名前が設定されていなかった。', 'label': 1})
db.insert({'text': '獠以外で傭兵時代から知っている人間はファルコンと呼んでいる。', 'label': 1})
db.insert({'text': 'たとえ君が誰であろうとも、オレにとっては君は侍女のサリナだよ', 'label': 1})
db.insert({'text': 'おたく、オリンピックか世界一かどうか知らんが、所詮素人の大会の大将だろうが！悪いが、オレはプロの世界一なんだ・・・', 'label': 1})
db.insert({'text': 'オレみたいな裏の世界の人間は・・・この街の汚れたところばかり見ているからね・・・こんな街、出て行きたくなる事もあるんだ。そんな時、此処へ来るのさ。すると、ここもまんざら捨てたもんじゃないと思えちまう・・・だから此処が、オレの一番好きな場所だ。', 'label': 1})
db.insert({'text': '新宿駅にある掲示板に「XYZ」の合言葉と連絡先を書くこと', 'label': 1})
db.insert({'text': 'かつての相棒の妹であった「槇村香（まきむら かおり）」は掲示板にシティハンターの助けを求めて訪れた人たちを救います', 'label': 1})
db.insert({'text': '冴羽獠のパートナー。男勝りな性格ではあるものも、誰に対しても優しく情が深い女性', 'label': 1})
db.insert({'text': '喫茶キャッツアイの面々', 'label': 1})
db.insert({'text': '伊集院 隼人（いじゅういん はやと）', 'label': 1})
db.insert({'text': '後の喫茶店キャッツアイの店主となる、海坊主またはファルコンと呼ばれる凄腕の傭兵で、冴羽獠と互角の腕をもつ凄腕の同業者', 'label': 1})
db.insert({'text': '後に海坊主の相棒となる、美人スイーパー。', 'label': 1})
db.insert({'text': '冴羽獠を自分の色香をエサに釣って、いつもタダ働きさせています。', 'label': 1})
db.insert({'text': '車の屋根から海坊主の頭が突き抜けることもあります。', 'label': 1})
db.insert({'text': 'なんでも器用にこなし、完璧に仕事を遂行するスイーパーですが', 'label': 1})
db.insert({'text': 'パートナーの槇村香の100tハンマー', 'label': 1})
db.insert({'text': '男がもっこりしなければ今の人類の繁栄はありえません!! そうです!! 男はもっこりしなければいけないのですっ!!', 'label': 1})
db.insert({'text': '絶えず股間をもっこりさせている冴羽獠', 'label': 1})
db.insert({'text': '遺言状の書き方をママに教えてもらっときな！！', 'label': 1})
db.insert({'text': '違法ドラッグ「エンジェル・ダスト」を売りさばくシンジケートの親衛隊「ユニオン」の将軍へと2人が迫ります', 'label': 1})
db.insert({'text': 'シティーハンターってのはな、おれたち、ふたりのコンビのことを言うんだぜ！！', 'label': 1})
db.insert({'text': 'よいかジェラール われわれはインペリアルクロス という陣形で戦う', 'label': 0})
db.insert({'text': '‥‥父上‥‥ 流し斬りが完全にはいったのに‥‥', 'label': 0})
db.insert({'text': '違う！もっと真剣になるのだ！', 'label': 0})
db.insert({'text': 'お前が次の皇帝だ。お前はクジンシーと戦わねばならん。', 'label': 0})
db.insert({'text': 'だが、今のお前では勝てん。私の力を受け継いで戦うのだ。いいな？', 'label': 0})
db.insert({'text': '先帝の無念を晴らす！', 'label': 0})
db.insert({'text': 'アリだー！', 'label': 0})
db.insert({'text': 'ハエのようにウルサイ奴ね。消えなさい！', 'label': 0})
db.insert({'text': '妹ロックブーケのカタキです。殺らせていただきます。', 'label': 0})
db.insert({'text': '最適なパラメータと最適な精度は下のコードで取得できる', 'label': 0})
db.insert({'text': '訓練データとテストデータに分割する', 'label': 0})
db.insert({'text': 'お兄様、私、ユリアンとずっと一緒にいたいと思います。', 'label': 0})
db.insert({'text': 'そ、そんな！トーマスカンパニーはどうするんだね。', 'label': 0})
db.insert({'text': '血と汗となみだを流せ！', 'label': 0})
db.insert({'text': 'なにが死の定めだ！もう聞きあきたぞ！', 'label': 0})
db.insert({'text': 'オレは死に場所を探していた。なんともいい場所じゃないか！', 'label': 0})
db.insert({'text': 'さよならなのだ', 'label': 0})
db.insert({'text': 'キサマがラスボスか！', 'label': 0})
db.insert({'text': '四つのアビスゲートを閉じ これですべて終わりのはずなのだが、星の位置のズレがわずかに残っている。 あと１つゲート残っているようなのだ。', 'label': 0})
db.insert({'text': 'サラ、帰ろう。', 'label': 0})
db.insert({'text': 'メールアドレスが公開されることはありません。 * が付いている欄は必須項目です', 'label': 0})
db.insert({'text': '等間隔の配列を作ることにより、x軸の作成等に結構使える', 'label': 0})
db.insert({'text': '10-fold の意味教えてください', 'label': 0})
db.insert({'text': '今回は言わずと知れたSVM(サポートベクターマシン)を試す', 'label': 0})
db.insert({'text': 'どのカーネルを使うか', 'label': 0})
db.insert({'text': '訓練データ数を変化させ, それぞれクロスバリデーションで決定したパラメーターに対して, 正答率, 学習時間, 平均予測時間を求めた', 'label': 0})
db.insert({'text': 'それぞれ次のようなコードで生成できる.', 'label': 0})
db.insert({'text': 'おそらく主人公キャラ毎に細部が違うと思われます', 'label': 0})
db.insert({'text': 'ロマサガ３ラストバトル前の一言。８人の主人公の中で１番印象に残っています。', 'label': 0})
db.insert({'text': '数値と数値の間では演算を行うことができますが、数値と文字列では四則演算を行うことは出来ません。', 'label': 0})
db.insert({'text': 'トレーニングデータでCVした時の平均スコア', 'label': 0})
db.insert({'text': '英語が読める方は公式のチュートリアルがおすすめです。', 'label': 0})
db.insert({'text': 'ただし、1段階目ではベストパラメータの値はそれほど重視しません。', 'label': 0})
db.insert({'text': '機械学習の王道。知らないでは許されない感を感じ、勉強', 'label': 0})
db.insert({'text': 'トレーニングデータとテストデータに分割．', 'label': 0})
db.insert({'text': 'F値は評価に非常によく使われています。', 'label': 0})
db.insert({'text': '伊集院隼人氏の平穏な一日の巻', 'label': 1})
db.insert({'text': 'CITY HUNTER', 'label': 1})
db.insert({'text': 'シティーハンター 100万人のスイーパー', 'label': 1})
db.insert({'text': '22世紀の未来からやってきたネコ型ロボット「ドラえもん」', 'label': 0})
db.insert({'text': '何をやらせてもまるで冴えない小学生の野比のび太', 'label': 0})
db.insert({'text': '愛よ消えないで、シティーハンターやってた頃よくカラオケで歌ったなあ♪', 'label': 1})
db.insert({'text': 'シティーハンターだとGET WILDだけど、やっぱベタだよな', 'label': 1})
db.insert({'text': '新宿を拠点にするスイーパー。様々な銃を使えるが、特にコルトパイソンを愛用している。持ち前の戦闘能力･推理力を用い、依頼された仕事をこなしていく。', 'label': 1})
db.insert({'text': 'やっぱり冴羽りょうかっこよすぎか…個人的には香よりも冴子が好きですな。', 'label': 1})
db.insert({'text': 'シティーハンター XYZ Edition、良いところで終わるな〜', 'label': 1})
db.insert({'text': '通称・海坊主又はファルコン。元傭兵で獠と互角の凄腕を持つ同業者', 'label': 1})
db.insert({'text': '失明の原因となる負傷も傭兵時代に獠を救出に向かった際に受けたことになっている', 'label': 1})
db.insert({'text': '今回は、シティーハンターの登場人物である、海坊主の魅力について迫ってみたいと思います。', 'label': 1})
db.insert({'text': '海坊主は主人公冴羽獠も認める始末屋(スイーパー)', 'label': 1})
db.insert({'text': '隼の字を取って「ファルコン」と名乗っています', 'label': 1})
db.insert({'text': '傭兵時代の上官の娘、氷室真希が外国に旅立つのを見送るシーンです', 'label': 1})
db.insert({'text': '氷室真希のバイオリンを聞いて傭兵時代の思い出がよみがえり、涙を流した稀有なシーンです', 'label': 1})
db.insert({'text': '主人公の冴羽獠が似たような経験をしても涙は流さないと思うので、海坊主は彼と比べて涙脆いと言えるかもしれません。', 'label': 1})
db.insert({'text': '漫画シティーハンターの登場人物、伊集院隼人（ファルコン）の通り名も海坊主である。 ', 'label': 1})
db.insert({'text': '主にバズーカなどの重火器を愛用する。口癖は「フン」。 ', 'label': 1})
db.insert({'text': 'そのため冴羽から「くそダコ」「ゆでダコ」とも呼ばれる', 'label': 1})
db.insert({'text': 'スイーパーとしては、獠とは基本的に敵対関係にあったようだが、日本での仕事では獠と手を組むことが多く、悪友のような間柄。', 'label': 1})
db.insert({'text': '俺には、この世界で愛する者を守りぬいていく度胸はない。', 'label': 1})
db.insert({'text': '依頼人に手を出す獠に100tハンマーで殴るなどの「天誅」を加えるのが定番。', 'label': 1})
db.insert({'text': '80年代最後のハンマーじゃ!! よっく味わえ～～!!', 'label': 1})
db.insert({'text': 'あのヤロウ～～！！！隠れて愛人がいたのかあ！！！', 'label': 1})
db.insert({'text': 'アスファルト タイヤをきりつけながら 暗闇走り抜ける', 'label': 1})
db.insert({'text': 'チープなスリルに身を任せても 明日におびえていたよ', 'label': 1})
db.insert({'text': 'It`s your pain or my pain or somebody`s pain', 'label': 1})
db.insert({'text': '誰かのために生きられるなら', 'label': 1})
db.insert({'text': 'It`s your dream or my dream or somebody`s dream', 'label': 1})
db.insert({'text': '何も怖くはない', 'label': 1})
db.insert({'text': 'Get wild and tough 独りでは解けない愛のパズルを抱いて', 'label': 1})
db.insert({'text': 'Get wild and tough この街でやさしさに甘えていたくはない', 'label': 1})
db.insert({'text': 'Get chance and luck 君だけが守れるものがどこかにあるさ', 'label': 1})
db.insert({'text': 'Get chance and luck ひとりでも傷ついた夢を取り戻すよ', 'label': 1})
db.insert({'text': '車のライトにKISSを投げては 車道で踊るあの子', 'label': 1})
db.insert({'text': '冷たい夜空をステージにして 哀しくおどけていたね', 'label': 1})
db.insert({'text': 'It`s your pain or my pain or somebody`s pain', 'label': 1})
db.insert({'text': '誰かのために愛せるのなら', 'label': 1})
db.insert({'text': 'It`s your dream or my dream or somebody`s dream', 'label': 1})
db.insert({'text': 'きっと強くなれる', 'label': 1})
db.insert({'text': 'Get wild and tough 独りでは消せない痛み心に抱いて', 'label': 1})
db.insert({'text': 'Get wild and tough この街で自由を持て余したくはない', 'label': 1})
db.insert({'text': 'Get chance and luck 君だけが守れるものを見つけ出したら', 'label': 1})
db.insert({'text': 'Get chance and luck ひとりでも傷ついた夢を取り戻すよ', 'label': 1})
db.insert({'text': 'Get wild and tough 独りでは解けない愛のパズルを抱いて', 'label': 1})
db.insert({'text': 'Get wild and tough この街でやさしさに甘えていたくはない', 'label': 1})
db.insert({'text': 'Get chance and luck 君だけが守れるものがどこかにあるさ', 'label': 1})
db.insert({'text': 'Get chance and luck ひとりでも傷ついた夢を取り戻すよ', 'label': 1})
db.insert({'text': 'Get wild and tough Get wild and tough', 'label': 1})
db.insert({'text': '冴羽役のオーディションには古川登志夫も参加しており、最終選考まで残った古川は、関係者から「（古川で）決まりでしょう」とまで言われていた', 'label': 1})
db.insert({'text': '新宿駅東口にある伝言板に「XYZ」の暗語と連絡方法を書き記す。', 'label': 1})
db.insert({'text': '依頼人の女性に手を出そうとしては相棒の槇村香に天誅を食らっている。', 'label': 1})
db.insert({'text': '「新宿の種馬」、「新宿の一発狼」、「恐怖のもっこり男」の異名を持つ。', 'label': 1})
db.insert({'text': 'もっこり。一発。ぼくチン。ボキ（＝僕）', 'label': 1})
db.insert({'text': '「シティーハンター」は、元々は親友のミック・エンジェルとアメリカでパートナーを組んでいた時の名である', 'label': 1})
db.insert({'text': '新宿でシティーハンターと呼ばれる超一流のプロのスイーパー（掃除屋・始末人）で、新宿のみならず世界中の闇社会でおそらくNo.1だろうと噂される程の屈指の凄腕である。', 'label': 1})
db.insert({'text': '香に対しては「男女（おとこおんな）」「唯一立たない女」などと子供みたいなからかい方（初期の頃に香に“もっこり”したことがある）をしたり', 'label': 1})
db.insert({'text': '超一流のスイーパーだが、盲腸になったり、同じ箇所を二度も骨折したり、香にハンマーで殴られたり、肛門にクッションの取れたイスが刺さることでケガをするなど三枚目な部分がある。', 'label': 1})
db.insert({'text': '獠は物心つかない幼少時代、とある中米の国で飛行機事故に遭い天涯孤独の身となる。', 'label': 1})
db.insert({'text': '小室哲哉', 'label': 1})
db.insert({'text': 'チープなスリル', 'label': 1})
db.insert({'text': 'りょうちゃんもっこり', 'label': 1})
db.insert({'text': 'タケコプター！！', 'label': 0})
db.insert({'text': 'セワシくん', 'label': 0})
db.insert({'text': 'からまげさん', 'label': 0})
db.insert({'text': 'まきむらかおり', 'label': 1})
db.insert({'text': 'そして誰もいなくなった', 'label': 0})
db.insert({'text': 'ほげほげ', 'label': 0})
db.insert({'text': '飛べない豚はただの豚だ', 'label': 0})
db.insert({'text': '千と千尋の神隠し', 'label': 0})
db.insert({'text': 'となりのトトロ', 'label': 0})
db.insert({'text': 'りょうちゃんもっこり', 'label': 0})
db.insert({'text': 'ドラえも～ん', 'label': 0})
db.insert({'text': 'アンパンマン新しい顔よ！！', 'label': 0})
db.insert({'text': 'プログラムを起動する', 'label': 0})
db.insert({'text': '藤子・F・不二雄', 'label': 0})
db.insert({'text': '劇場版のび太の日本誕生', 'label': 0})
db.insert({'text': 'ドラえもんチャンネル', 'label': 0})
db.insert({'text': 'あの青年は、人の幸せを願い、人の不幸を悲しむことのできる人間だ', 'label': 0})
db.insert({'text': 'のび太にも良いところが一つだけある。それは彼は反省するんです。', 'label': 0})

print db.all()
