# -*- coding: utf-8 -
from tinydb import TinyDB, Query

db = TinyDB('db/dataset_category.json')
db.purge()
db.insert({'text': 'ストーリーについて', 'label': 1})
db.insert({'text': 'あらすじについて知りたい', 'label': 1})
db.insert({'text': 'あらすじ', 'label': 1})
db.insert({'text': '話について', 'label': 1})
db.insert({'text': 'どんな話だっけ', 'label': 1})
db.insert({'text': 'どんなストーリーだったか', 'label': 1})
db.insert({'text': 'ストーリー', 'label': 1})
db.insert({'text': '各話のあらすじ', 'label': 1})
db.insert({'text': 'どんな話か', 'label': 1})
db.insert({'text': '登場人物', 'label': 2})
db.insert({'text': '人物について', 'label': 2})
db.insert({'text': 'キャラクター', 'label': 2})
db.insert({'text': 'キャラについて', 'label': 2})
db.insert({'text': '登場する人', 'label': 2})
db.insert({'text': '主人公', 'label': 2})
db.insert({'text': '人', 'label': 2})
db.insert({'text': '人について', 'label': 2})
db.insert({'text': 'キャラ', 'label': 2})
db.insert({'text': '登場人物について', 'label': 2})
db.insert({'text': 'どんな人', 'label': 2})

#print db.all()

db = TinyDB('db/dataset_answer.json')
db.purge()
db.insert({'category_id': 1, 'text': 'りょうについて', 'label': 1})
db.insert({'category_id': 1, 'text': 'もっこりの人', 'label': 1})
db.insert({'category_id': 1, 'text': '主人公', 'label': 1})
db.insert({'category_id': 1, 'text': 'シティーハンター', 'label': 1})
db.insert({'category_id': 1, 'text': '冴羽獠', 'label': 1})
db.insert({'category_id': 1, 'text': 'リョウ', 'label': 1})
db.insert({'category_id': 1, 'text': 'さえばりょう', 'label': 1})
db.insert({'category_id': 1, 'text': 'りょうちゃん', 'label': 1})
db.insert({'category_id': 1, 'text': 'さえば', 'label': 1})
db.insert({'category_id': 1, 'text': '冴羽', 'label': 1})
db.insert({'category_id': 1, 'text': '冴羽リョウ', 'label': 1})
db.insert({'category_id': 1, 'text': '冴羽りょう', 'label': 1})
db.insert({'category_id': 1, 'text': '100tハンマー', 'label': 2})
db.insert({'category_id': 1, 'text': 'ハンマー', 'label': 2})
db.insert({'category_id': 1, 'text': '跳弾', 'label': 2})
db.insert({'category_id': 1, 'text': '槇村の妹', 'label': 2})
db.insert({'category_id': 1, 'text': 'ヒロイン', 'label': 2})
db.insert({'category_id': 1, 'text': '相棒', 'label': 2})
db.insert({'category_id': 1, 'text': '唯一もっこりしない女性', 'label': 2})
db.insert({'category_id': 1, 'text': '天誅', 'label': 2})
db.insert({'category_id': 1, 'text': 'メインヒロイン', 'label': 2})
db.insert({'category_id': 1, 'text': '槇村香', 'label': 2})
db.insert({'category_id': 1, 'text': 'まきむらかおり', 'label': 2})
db.insert({'category_id': 1, 'text': 'かおり', 'label': 2})
db.insert({'category_id': 1, 'text': '獠の相棒', 'label': 3})
db.insert({'category_id': 1, 'text': '最初に死んだ', 'label': 3})
db.insert({'category_id': 1, 'text': '死んだ', 'label': 3})
db.insert({'category_id': 1, 'text': 'エンジェルダスト', 'label': 3})
db.insert({'category_id': 1, 'text': '冴子の相棒', 'label': 3})
db.insert({'category_id': 1, 'text': 'ユニオンテオーペ', 'label': 3})
db.insert({'category_id': 1, 'text': 'コルト・ローマン', 'label': 3})
db.insert({'category_id': 1, 'text': '香の兄', 'label': 3})
db.insert({'category_id': 1, 'text': '元刑事', 'label': 3})
db.insert({'category_id': 1, 'text': '元警察官', 'label': 3})
db.insert({'category_id': 1, 'text': 'ジェネラルに殺された', 'label': 3})
db.insert({'category_id': 1, 'text': 'スイーパー', 'label': 4})
db.insert({'category_id': 1, 'text': 'アメリカNo.1のスイーパー', 'label': 4})
db.insert({'category_id': 1, 'text': 'アメリカ人', 'label': 4})
db.insert({'category_id': 1, 'text': 'エンジェルダストを打たれる', 'label': 4})
db.insert({'category_id': 1, 'text': 'エンジェルダストを投与される', 'label': 4})
db.insert({'category_id': 1, 'text': 'デザートイーグル', 'label': 4})
db.insert({'category_id': 1, 'text': '香に惚れる', 'label': 4})
db.insert({'category_id': 1, 'text': 'カオリにほれる', 'label': 4})
db.insert({'category_id': 1, 'text': 'かおりにほれる', 'label': 4})
db.insert({'category_id': 1, 'text': '恋人のいる女性に手を出す', 'label': 4})
db.insert({'category_id': 1, 'text': 'ファルコン', 'label': 5})
db.insert({'category_id': 1, 'text': '元傭兵', 'label': 5})
db.insert({'category_id': 1, 'text': '獠の互角', 'label': 5})
db.insert({'category_id': 1, 'text': '喫茶キャッツアイの店主', 'label': 5})
db.insert({'category_id': 1, 'text': '伊集院隼人', 'label': 5})
db.insert({'category_id': 1, 'text': '海坊主', 'label': 5})
db.insert({'category_id': 1, 'text': 'バズーカ', 'label': 5})
db.insert({'category_id': 1, 'text': '機関銃', 'label': 5})
db.insert({'category_id': 1, 'text': '銃火器', 'label': 5})
db.insert({'category_id': 1, 'text': 'トラップの名手', 'label': 5})
db.insert({'category_id': 1, 'text': 'たこ坊主', 'label': 5})
db.insert({'category_id': 1, 'text': 'タコ坊主', 'label': 5})
db.insert({'category_id': 1, 'text': 'ハチ公', 'label': 5})
db.insert({'category_id': 1, 'text': '猫が苦手', 'label': 5})
db.insert({'category_id': 1, 'text': '女性が苦手', 'label': 5})
db.insert({'category_id': 1, 'text': '弱視', 'label': 5})
db.insert({'category_id': 1, 'text': '失明', 'label': 5})
db.insert({'category_id': 1, 'text': '苗字は不明', 'label': 6})
db.insert({'category_id': 1, 'text': '海坊主と結婚', 'label': 6})
db.insert({'category_id': 1, 'text': '喫茶キャッツアイ', 'label': 6})
db.insert({'category_id': 1, 'text': '海坊主に育てられた', 'label': 6})
db.insert({'category_id': 1, 'text': '美樹', 'label': 6})
db.insert({'category_id': 1, 'text': '海坊主の相棒', 'label': 6})
db.insert({'category_id': 1, 'text': 'みき', 'label': 6})
db.insert({'category_id': 1, 'text': '美人スイーパー', 'label': 6})
db.insert({'category_id': 1, 'text': '怪盗305号', 'label': 7})
db.insert({'category_id': 1, 'text': '怪盗', 'label': 7})
db.insert({'category_id': 1, 'text': '空飛ぶオシリ', 'label': 7})
db.insert({'category_id': 1, 'text': '空飛ぶお尻', 'label': 7})
db.insert({'category_id': 1, 'text': 'そらとぶおしり', 'label': 7})
db.insert({'category_id': 1, 'text': '麻生 かすみ', 'label': 7})
db.insert({'category_id': 1, 'text': 'かすみ', 'label': 7})
db.insert({'category_id': 1, 'text': '麻生', 'label': 7})
db.insert({'category_id': 1, 'text': 'あそう かすみ', 'label': 7})
db.insert({'category_id': 1, 'text': 'レオタード', 'label': 7})
db.insert({'category_id': 1, 'text': '黒いチューリップ', 'label': 7})
db.insert({'category_id': 1, 'text': '崇司', 'label': 7})
db.insert({'category_id': 1, 'text': '獠に心を奪われた', 'label': 7})
db.insert({'category_id': 1, 'text': '警視庁のメギツネ', 'label': 8})
db.insert({'category_id': 1, 'text': '警視庁の女狐', 'label': 8})
db.insert({'category_id': 1, 'text': 'めぎつね', 'label': 8})
db.insert({'category_id': 1, 'text': '女狐', 'label': 8})
db.insert({'category_id': 1, 'text': '美人刑事', 'label': 8})
db.insert({'category_id': 1, 'text': 'のがみさえこ', 'label': 8})
db.insert({'category_id': 1, 'text': '野上 冴子', 'label': 8})
db.insert({'category_id': 1, 'text': 'さえこ', 'label': 8})
db.insert({'category_id': 1, 'text': 'サエコ', 'label': 8})
db.insert({'category_id': 1, 'text': 'のがみ', 'label': 8})
db.insert({'category_id': 1, 'text': '槇村秀幸の同僚', 'label': 8})
db.insert({'category_id': 1, 'text': '色仕掛', 'label': 8})
db.insert({'category_id': 1, 'text': 'いろじかけ', 'label': 8})
db.insert({'category_id': 1, 'text': '投げナイフ', 'label': 8})
db.insert({'category_id': 1, 'text': 'さえこの妹', 'label': 9})
db.insert({'category_id': 1, 'text': '冴子の妹', 'label': 9})
db.insert({'category_id': 1, 'text': 'さえこのいもうと', 'label': 9})
db.insert({'category_id': 1, 'text': '野上 麗香', 'label': 9})
db.insert({'category_id': 1, 'text': 'のがみれいか', 'label': 9})
db.insert({'category_id': 1, 'text': 'のがみ れいか', 'label': 9})
db.insert({'category_id': 1, 'text': 'れいか', 'label': 9})
db.insert({'category_id': 1, 'text': '元刑事で探偵', 'label': 9})
db.insert({'category_id': 1, 'text': '探偵', 'label': 9})
db.insert({'category_id': 1, 'text': 'RN探偵社', 'label': 9})
db.insert({'category_id': 1, 'text': '友村刑事の相棒', 'label': 9})
db.insert({'category_id': 1, 'text': '隣のマンション', 'label': 9})
db.insert({'category_id': 1, 'text': 'となりのマンション', 'label': 9})
db.insert({'category_id': 1, 'text': '男嫌い', 'label': 9})
db.insert({'category_id': 1, 'text': '獠が好き', 'label': 9})
db.insert({'category_id': 1, 'text': 'リョウが好き', 'label': 9})
db.insert({'category_id': 2, 'text': 'XYZ', 'label': 10})
db.insert({'category_id': 2, 'text': '通り魔', 'label': 10})
db.insert({'category_id': 2, 'text': '犯人探し', 'label': 10})
db.insert({'category_id': 2, 'text': 'トップレスバー', 'label': 10})
db.insert({'category_id': 2, 'text': '指の間', 'label': 10})
db.insert({'category_id': 2, 'text': '指と指', 'label': 10})
db.insert({'category_id': 2, 'text': '指の骨の間', 'label': 10})
db.insert({'category_id': 2, 'text': '菜摘', 'label': 10})
db.insert({'category_id': 2, 'text': '私が、私がこの手で、妹の仇を討ってやるわ！', 'label': 10})
db.insert({'category_id': 2, 'text': 'おたくが手を汚すほどの値打ちもない', 'label': 10})
db.insert({'category_id': 2, 'text': 'あいつは、おたくが手を汚すほどの値打ちもない。だからこそ、俺のような男がいるのさ', 'label': 10})
db.insert({'category_id': 2, 'text': '私を殺して！！美女に照準は似合わない', 'label': 11})
db.insert({'category_id': 2, 'text': '第2話', 'label': 11})
db.insert({'category_id': 2, 'text': '清水美津子', 'label': 11})
db.insert({'category_id': 2, 'text': 'しみずなつこ', 'label': 11})
db.insert({'category_id': 2, 'text': '去勢薬', 'label': 11})
db.insert({'category_id': 2, 'text': '去勢', 'label': 11})
db.insert({'category_id': 2, 'text': '死の商人', 'label': 11})
db.insert({'category_id': 2, 'text': '私を殺して', 'label': 11})
db.insert({'category_id': 2, 'text': 'モハメド', 'label': 11})
db.insert({'category_id': 2, 'text': '私……ワクチンが完成したら、あなたのこと、研究してみます……', 'label': 11})
db.insert({'category_id': 2, 'text': '愛よ消えないで！明日へのテンカウント」', 'label': 12})
db.insert({'category_id': 2, 'text': '愛よ消えないで！', 'label': 12})
db.insert({'category_id': 2, 'text': 'ボクシング', 'label': 12})
db.insert({'category_id': 2, 'text': 'ボクサー', 'label': 12})
db.insert({'category_id': 2, 'text': '稲垣', 'label': 12})
db.insert({'category_id': 2, 'text': 'いながき', 'label': 12})
db.insert({'category_id': 2, 'text': '荻野', 'label': 12})
db.insert({'category_id': 2, 'text': '岩崎めぐみ', 'label': 12})
db.insert({'category_id': 2, 'text': '女医', 'label': 12})
db.insert({'category_id': 2, 'text': 'チャンピオン', 'label': 12})
db.insert({'category_id': 2, 'text': 'タイトルマッチ', 'label': 12})
db.insert({'category_id': 2, 'text': '狙撃', 'label': 12})
db.insert({'category_id': 2, 'text': 'こめかみに狙撃', 'label': 12})
db.insert({'category_id': 2, 'text': 'おたくの命がある限り、俺を恋人だと思ってくれ', 'label': 12})
db.insert({'category_id': 2, 'text': 'こいつを貴様の耳にぶち込んでやる', 'label': 12})
db.insert({'category_id': 2, 'text': '第3話', 'label': 12})
db.insert({'category_id': 2, 'text': '純金の弾は貫通せずに、貴様の頭蓋骨にへばり付く', 'label': 12})
db.insert({'category_id': 2, 'text': '美女蒸発!!　ブティックは闇への誘い', 'label': 13})
db.insert({'category_id': 2, 'text': '第4話', 'label': 13})
db.insert({'category_id': 2, 'text': '美女が行方不明', 'label': 13})
db.insert({'category_id': 2, 'text': 'かおり初登場', 'label': 13})
db.insert({'category_id': 2, 'text': '香が初登場', 'label': 13})
db.insert({'category_id': 2, 'text': 'ブティック・オルフェ', 'label': 13})
db.insert({'category_id': 2, 'text': '更衣室に落とし穴', 'label': 13})
db.insert({'category_id': 2, 'text': 'マジックミラー', 'label': 13})
db.insert({'category_id': 2, 'text': '槇村香の初登場', 'label': 13})
db.insert({'category_id': 2, 'text': '10ｔハンマー', 'label': 13})
db.insert({'category_id': 2, 'text': 'まだ言うか！俺は女だ！', 'label': 13})
db.insert({'category_id': 2, 'text': 'グッバイ槇村　雨の夜に涙のバースデー', 'label': 14})
db.insert({'category_id': 2, 'text': '赤いペガサス', 'label': 14})
db.insert({'category_id': 2, 'text': '相棒の死', 'label': 14})
db.insert({'category_id': 2, 'text': '槇村が死ぬ', 'label': 14})
db.insert({'category_id': 2, 'text': 'ジェネラル', 'label': 14})
db.insert({'category_id': 2, 'text': '新しい相棒', 'label': 14})
db.insert({'category_id': 2, 'text': '来年のバースデーは、地獄で祝うことになるかもしれんぞ', 'label': 14})
db.insert({'category_id': 2, 'text': '槇村 死亡', 'label': 14})
db.insert({'category_id': 2, 'text': '香の過去', 'label': 14})
db.insert({'category_id': 2, 'text': 'かおりの過去', 'label': 14})
db.insert({'category_id': 2, 'text': '悪魔に魂を売る気はない。悪魔はドブネズミに劣る！', 'label': 14})
db.insert({'category_id': 2, 'text': 'しばらくの間、地獄は寂しいかもしれんが、すぐに賑やかにしてやるよ……槇村', 'label': 14})
db.insert({'category_id': 2, 'text': '第5話', 'label': 14})
db.insert({'category_id': 2, 'text': '地獄は寂しい', 'label': 14})
db.insert({'category_id': 2, 'text': '恋しない女優　希望へのラストショット', 'label': 15})
db.insert({'category_id': 2, 'text': '佐藤由美子', 'label': 15})
db.insert({'category_id': 2, 'text': '女優', 'label': 15})
db.insert({'category_id': 2, 'text': '海坊主 初登場', 'label': 15})
db.insert({'category_id': 2, 'text': '恋人', 'label': 15})
db.insert({'category_id': 2, 'text': '恋人をひきずる', 'label': 15})
db.insert({'category_id': 2, 'text': '死んだ恋人', 'label': 15})
db.insert({'category_id': 2, 'text': 'ボディーガード', 'label': 15})
db.insert({'category_id': 2, 'text': '撮影中に殺してもらう', 'label': 15})
db.insert({'category_id': 2, 'text': 'また、死にたくなった呼んでくれ。女性へのアフターサービスは、万全なんだ', 'label': 15})
db.insert({'category_id': 2, 'text': '女性へのアフターサービス', 'label': 15})
db.insert({'category_id': 2, 'text': '女優の話', 'label': 15})
db.insert({'category_id': 2, 'text': '第6話', 'label': 15})
db.insert({'category_id': 2, 'text': '心ふるえる銃声　悲しきロンリーガール', 'label': 16})
db.insert({'category_id': 2, 'text': '運転手', 'label': 16})
db.insert({'category_id': 2, 'text': '萩尾', 'label': 16})
db.insert({'category_id': 2, 'text': 'はぎお', 'label': 16})
db.insert({'category_id': 2, 'text': 'あまち', 'label': 16})
db.insert({'category_id': 2, 'text': '天知', 'label': 16})
db.insert({'category_id': 2, 'text': '次期総理', 'label': 16})
db.insert({'category_id': 2, 'text': '心が震えた', 'label': 16})
db.insert({'category_id': 2, 'text': 'こころがふるえた', 'label': 16})
db.insert({'category_id': 2, 'text': '脅迫', 'label': 16})
db.insert({'category_id': 2, 'text': '偽装殺人', 'label': 16})
db.insert({'category_id': 2, 'text': '男からの依頼', 'label': 16})
db.insert({'category_id': 2, 'text': 'マンホールがずれる', 'label': 16})
db.insert({'category_id': 2, 'text': 'こ、殺してやる！誰だ俺をハメやがった奴は！', 'label': 16})
db.insert({'category_id': 2, 'text': '第7話', 'label': 16})
db.insert({'category_id': 2, 'text': '美人に百発百中(ワンホールショット)？！　女刑事には手を出すな」', 'label': 17})
db.insert({'category_id': 2, 'text': '野上冴子 初登場', 'label': 17})
db.insert({'category_id': 2, 'text': 'さえこ 初登場', 'label': 17})
db.insert({'category_id': 2, 'text': 'さえこ初登場', 'label': 17})
db.insert({'category_id': 2, 'text': 'ウラメニア共和国のスパイ', 'label': 17})
db.insert({'category_id': 2, 'text': 'マイクロチップ', 'label': 17})
db.insert({'category_id': 2, 'text': '秘宝展', 'label': 17})
db.insert({'category_id': 2, 'text': '宝冠', 'label': 17})
db.insert({'category_id': 2, 'text': 'ワンホールショット', 'label': 17})
db.insert({'category_id': 2, 'text': 'ワン・オブ・サウザンド', 'label': 17})
db.insert({'category_id': 2, 'text': '第8話', 'label': 17})
db.insert({'category_id': 2, 'text': '女刑事', 'label': 17})
db.insert({'category_id': 2, 'text': 'ギャンブルクィーン　華麗なる恋の賭け', 'label': 18})
db.insert({'category_id': 2, 'text': '鬼英会', 'label': 18})
db.insert({'category_id': 2, 'text': 'カジノ', 'label': 18})
db.insert({'category_id': 2, 'text': '牧野陽子', 'label': 18})
db.insert({'category_id': 2, 'text': 'まきの', 'label': 18})
db.insert({'category_id': 2, 'text': '高円会', 'label': 18})
db.insert({'category_id': 2, 'text': 'ディーラー', 'label': 18})
db.insert({'category_id': 2, 'text': 'ヴァンパイア竜', 'label': 18})
db.insert({'category_id': 2, 'text': 'ギャンブラー', 'label': 18})
db.insert({'category_id': 2, 'text': '竜', 'label': 18})
db.insert({'category_id': 2, 'text': 'ノワールの13、お客様にお似合いのナンバーですわね', 'label': 18})
db.insert({'category_id': 2, 'text': '普通の女になったんだな、陽子……幸せにな', 'label': 18})
db.insert({'category_id': 2, 'text': '第9話', 'label': 18})
